### PR TITLE
Convert `--generate-completion` flag to subcommand and add docs/tests

### PR DESCRIPTION
**Pull request by JamyGolden**
@henry-hsieh I've changed it from a flag to a subcommand since it's more of an action and shouldn't be used with other subcommands.

I've also added docs and tests. Are you happy with the change?

### CODE REVIEW

**Comment by JamyGolden** [comment]
:+1: ah yes forgot about that. I've also removed the scripts except for the modified `contrib/completion/tinty.bash` script since the others can be generated with tinty itself.

**Comment by henry-hsieh** [comment]
Looks good. Do you plan to put the completion scripts into release tarball? I have seen some Rust CLI utilities do that. Or let user generate or clone from `contrib` manually.

**Comment by JamyGolden** [comment]
I was thinking that people could generate the shell completion using `tinty` when they wanted it (for the non-dynamic completions) and copy from the `contrib` dir in the repo manually for the dynamic completions. That seems simple enough to me but I personally don't use any completions so I may be out of the loop with what's typically done. What have you found is most common?

**Comment by henry-hsieh** [comment]
I think most people just ignore the completions. Never mind!

**Comment by JamyGolden** [comment]
I appreciate all the feedback you've given with everything! I've re-added the completions to `contrib/completion/*` and I've made sure to add those into the release tarball. In future I can consider optimising but for now it's actually easier to just have them all exist there rather than only the ones that are modified.

**Pull request merged**
